sonar.projectKey=gluten5659_go-project-244
sonar.organization=golearnorg

sonar.sources=.
sonar.exclusions=**/*_test.go,bin/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=cmd/**,**/testutil/**
